# Resourceの定義
resources:
# Git Resourceの定義
- name: hello
  type: git
  source:
    uri: https://github.com/disc99/hello-concourse.git
- name: result
  type: git
  source:
    uri: git@gist.github.com:33490110580cc9a89c7dde10ba897de7.git
    private_key: {{github-private-key}}
    branch: master

# Jobの定義
jobs:
- name: hello-job
  public: true # UI上でJobの結果をログイン不要で公開するかどうか
  plan:
  - get: hello
    trigger: true # Resourceに変更があれば自動でジョブを実行するかどうか
  - get: result # 出力結果のGitをpull (次に定義する)
  - task: run-hello
    file: hello/hello.yml
  - task: commit-log # 出力結果ファイルをGitにコミットするTask
    file: hello/commit-log.yml
  - put: result # 出力結果のGitのpush
    params:
      repository: updated-result

- name: show-result-job # 新規ジョブ
  public: true
  plan:
  - get: hello    
  - get: result
    trigger: true
    passed: [ hello-job ]
  - task: show-result
    file: hello/show-result.yml